#!/bin/bash

FIXED_INFO_WIDTH=33
MIN_MP_WIDTH=25

c_reset='\033[0m'
c_mount='\033[1;34m'
c_size='\033[0;32m'
c_human='\033[1;30m'

term_width=$(tput cols 2>/dev/null || echo ${COLUMNS:-80})

min_tile_width=$((FIXED_INFO_WIDTH + MIN_MP_WIDTH))

num_cols=$((term_width / min_tile_width))
if [[ $num_cols -lt 1 ]]; then num_cols=1; fi

actual_tile_width=$((term_width / num_cols))

mp_width=$((actual_tile_width - FIXED_INFO_WIDTH - 1))

main() {
    local fmt_str="${c_mount}%-${mp_width}.${mp_width}s${c_reset} ${c_size}%11s MB${c_reset} ${c_human}%-17s${c_reset}\n"

    mapfile -t disks < <(
        LC_ALL=C df --output=target,used,size | \
        grep -E '^/media|^/$' | \
        sort -V | \
        while read -r mp used total; do
            mb=$((used / 1024))
            mb_pretty=$(printf "%'.f" $mb)
            
            h_used=$(numfmt --from-unit=1024 --to=iec --format="%.1f" "$used")
            h_total=$(numfmt --from-unit=1024 --to=iec --format="%.1f" "$total")
            
            compact_str="[${h_used} / ${h_total}]"

            printf "$fmt_str" "$mp" "$mb_pretty" "$compact_str"
        done
    )

    local count=0
    for disk in "${disks[@]}"; do
        echo -ne "$disk"
        echo -ne " " 

        ((count++))

        if [[ $((count % num_cols)) -eq 0 ]]; then
            echo "" 
        fi
    done
    
    if [[ $((count % num_cols)) -ne 0 ]]; then
        echo ""
    fi
}

main
